baseURL = "https://intsuki.netlify.com/"
languageCode = "en-us"
title = "Intsuki"
theme = "base"
# Theme related settings below.

[params]
  description = "Peter Yuanzong Li"
  mainIcon = "/img/hugo.png"